### ISSUE TITLE
fix : chatbot display issue

### ISSUE THREAD

**Issue by ayush-oswal** [piyushgarg-dev/leetcode-whisper-chrome-extension#108]
The top of the chatbot is being cut by the screen, did try to add margin to it but showed no effect.

Steps to reproduce : 
Setup the extension, i used dist folder obtained from pnpm run build on the load unpacked. Also i am using windows

<img width="960" alt="1" src="https://github.com/user-attachments/assets/854482c3-1217-46bb-986b-72bc48493161">

Guide me if i am wrong @piyushgarg-dev @ruru-m07

**Comment by ruru-m07** [comment]
@ayush-oswal what is your screen zoom? Like 100% or less then?

**Comment by ayush-oswal** [comment]
it was 90%, reduced it to 80% and now it is rendering properly
