### ISSUE TITLE
[Feature Request] | Disable during contest

### ISSUE THREAD

**Issue by eaniket** [piyushgarg-dev/leetcode-whisper-chrome-extension#16]
1. Check if the problem is from an ongoing contest(maybe by using the HTML content of the page)
2. If yes, reply with a warning about not using the extension during the contest.

**Comment by ayush-oswal** [comment]
@eaniket I guess the url of contests have /contest included in them and this extension only activates on leetocode/problems/*

**Comment by KshKnsl** [comment]
No it is has /contest 
![image](https://github.com/user-attachments/assets/3134fb6b-5cff-429f-ac9d-c322e45312a6)
