### ISSUE TITLE
feat(migration(modal)): from modal `chatgpt-4o-latest` to `gemini-1.0-pro`.

### ISSUE THREAD

**Issue by ruru-m07** [piyushgarg-dev/leetcode-whisper-chrome-extension#71]
### What wrong???

if we reach the limit we see this error.
![PepeCRY~1](https://cdn.discordapp.com/emojis/1282264675769258014.webp?size=48&name=PepeCRY%7E1)

![image](https://github.com/user-attachments/assets/29ddf7cd-1315-4288-aa0c-45b2d3e96f79)

### What should we do?

we can use another free modal like `Gemini-1.0-pro` where users can access their API KEY from [aistudio](https://aistudio.google.com/app/apikey)

#### [**pricing** ](https://ai.google.dev/pricing#1_0pro)
![image](https://github.com/user-attachments/assets/d81aa757-c29e-49a8-b63f-66b7abece1e2)

**and IG this is more than enough**

### What will these changes expect?

well now user need to add their Gemini API key instead of the expensive open-AI key :)

**Comment by ruru-m07** [comment]
@piyushgarg-dev If you agree with this feature, I am happy to work on it. 😊 You can assign this issue to me, and don't hesitate to close it.

**Comment by piyushgarg-dev** [comment]
Sure, go ahead

**Comment by venkat2305** [comment]
can you also add other free providers like open-router , groq.

**Comment by heygogu** [comment]
@ruru-m07 hey , I was working on dynamic language feature .. but I ended up in rebase errors while pushing code . Tried very hard but the branch had conflicts again and again whenever someone else's PR was merged.

You can add this in yours for dynamic language support. i hope this helps

`document.querySelector('[data-mode-id]')?.getAttribute('data-mode-id') as string`
 

It will get the language selected from leetcode dropdown.

**Comment by thekbbohara** [comment]
@ruru-m07 keep both, openai and Gemini + and other, like zed editor. User should have option to use whatever model they have and want

**Comment by ruru-m07** [comment]
> @ruru-m07 keep both, openai and Gemini + and other, like zed editor. User should have option to use whatever model they have and want

yeh will add more 

![image](https://github.com/user-attachments/assets/47fc83fb-7830-435d-a60d-bb9c12b78c0c)

**Comment by piyushgarg-dev** [comment]
Hey @ruru-m07, How is this going?

**Comment by vishal065** [comment]
does Gemini API give a streaming response?? was having a hard time getting streaming response
